name: PHPUnit

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']
    runs-on: ubuntu-latest
    env:
      DEVELOPMENT_BRANCH: 6.2-BoostDay

    steps:
    - name: Clone development
      run: git clone -b $DEVELOPMENT_BRANCH https://github.com/shopware/development.git && cd development && rm -rf platform

    - name: Clone platform
      uses: actions/checkout@v2
      with:
        path: development/platform

    - name: Fix platform for composer
      run: |
        cd development/platform
        git fetch --prune --unshallow
        git checkout master
        git checkout -
        cd ..
        git reset --hard @
  
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, prestissimo
        coverage: none

    - name: Start MySQL
      run: ./development/platform/.github/setup-db.sh mysql:5.7
    
    - name: Start Elasticsearch
      run: ./development/platform/.github/setup-es.sh elastic/elasticsearch:7.1.1

    - name: Install Shopware
      run: |
        cd development
        ./psh.phar init-composer
        if [[ ! -h vendor/shopware/platform ]]; then echo 'vendor/shopware/platform should be a symlink'; exit 1; fi
        nohup php -S localhost:8000 -t public > phpd.log 2>&1 &
        ./psh.phar init --DB_HOST=127.0.0.1 --DB_USER=root --DB_PASSWORD=shopware --SHOPWARE_ES_HOSTS=localhost:9200
     
    - name: Run PHPUnit
      run: cd development && php -d memory_limit=-1 vendor/bin/phpunit --configuration vendor/shopware/platform/phpunit.xml.dist --exclude-group needsWebserver
